"""
Exercício 1:
Crie uma variável do tipo lista com 5 elementos (você escolhe quais serão). Imprima na tela o elemento e sua respectiva posição na lista. 
Exemplo: para a lista [1, 3, 6, “H”, [7,7,7]] a saída deve ser:
>>> Elemento 1 na posição 0
>>> Elemento 3 na posição 1
>>> Elemento 6 na posição 2
>>> Elemento “H” na posição 3
"""

variaveis = ["Julia", 257, 8.3698, [-4, 2, 0, 12], (1990, 1992, 1998)]

print(f"Elemento {variaveis[0]} na posição 0")
print(f"Elemento {variaveis[1]} na posição 1")
print(f"Elemento {variaveis[2]} na posição 2")
print(f"Elemento {variaveis[3]} na posição 3")
print(f"Elemento {variaveis[4]} na posição 4")